# Main Configurations

  theme: jekyll-theme-neo

  title: Neo theme
  description: Neo is a clean, responsive Jekyll theme for GitHub Pages.

  show_downloads: true
  # show_downloads: ["true" or "false" (unquoted)]
    # indicate whether to provide a download URL.

  # google_analytics: [Your Google Analytics tracking ID]
    # fill in your Google Analytics ID to track your website
    # using Google Analytics.

  # github:
    # zip_url: http://example.com/download.zip
    # another_url: another value

  theme_color: '#222'
  color_scheme: 'light dark'
  # favicon: favicon.ico
  # manifest: manifest.json

  sass:
    style: compressed

  # Exclude these files from production site.
  exclude:
  - "*.gem"
  - "*.gemspec"
  - ".sass-cache"
  - Gemfile
  - Gemfile.lock
  - CNAME
  - ".github"
  - ".backup"
  - ".local"
  - ".bundle"
  - vendor

  # plugins:
  # - jekyll-paginate
  # - jekyll-sitemap

# Custom Configurations

  nickname: Neo
    # a shortname for your site.
