# Main Configurations

  title: [The title of your site]
  description: [A short description of your site's purpose]

  remote_theme: techie-joe/neo

  remote_theme_build_revision: {{ site.github.build_revision }}

  plugins:
  - jekyll-remote-theme
    # add jekyll-remote-theme to the existing plugins list if
    # you already have one.

  # show_downloads: ["true" or "false" (unquoted)]
    # indicate whether to provide a download URL.

  # google_analytics: [Your Google Analytics tracking ID]
    # fill in your Google Analytics ID to track your website
    # using Google Analytics.

  # github:
    # zip_url: http://example.com/download.zip
    # another_url: another value

# Custom Configurations

  # nickname: [Neo]
    # a shortname for your site.